package GUI;

import members.Appointment;
import members.Customer;
import methods.Notice;
import methods.connectMethod;

import javax.swing.*;
import java.awt.*;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Objects;

/**
 * @author Ché Alexander
 */
public class AppointmentGUI extends javax.swing.JFrame {

    Notice popup = new Notice();

    /**
     * Creates new form AppointmentGUI
     */
    public AppointmentGUI() {
        initComponents();
        
        // Get size of the screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        // Determine the new location of the window
        int w, h, x, y;
        w = this.getSize().width;
        h = this.getSize().height;
        x = (dim.width - w) / 2;
        y = (dim.height - h) / 2;
        // Move the Window
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yesno = new javax.swing.ButtonGroup();
        east = new javax.swing.JPanel();
        north = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        west = new javax.swing.JPanel();
        south = new javax.swing.JPanel();
        submit = new javax.swing.JButton();
        center = new javax.swing.JPanel();
        fullname = new javax.swing.JLabel();
        tfFullname = new javax.swing.JTextField();
        phnum = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        tfemail = new javax.swing.JTextField();
        text0 = new javax.swing.JLabel();
        yes = new javax.swing.JCheckBox();
        no = new javax.swing.JCheckBox();
        appoinment = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        time = new javax.swing.JComboBox<>();
        text1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        tfPhnum = new javax.swing.JFormattedTextField();
        emailError = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        tfid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Application Form");

        east.setBackground(new java.awt.Color(204, 255, 255));
        east.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(east, java.awt.BorderLayout.LINE_END);

        north.setBackground(new java.awt.Color(153, 255, 255));
        north.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setText("Appointment Form");
        north.add(title);

        getContentPane().add(north, java.awt.BorderLayout.PAGE_START);

        west.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(west, java.awt.BorderLayout.LINE_START);

        south.setBackground(new java.awt.Color(204, 255, 255));

        submit.setBackground(new java.awt.Color(204, 255, 255));
        submit.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        submit.setForeground(new java.awt.Color(0, 0, 0));
        submit.setText("Submit");
        submit.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        south.add(submit);

        getContentPane().add(south, java.awt.BorderLayout.PAGE_END);

        center.setBackground(new java.awt.Color(204, 204, 204));
        center.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createTitledBorder("")));
        center.setForeground(new java.awt.Color(255, 255, 255));

        fullname.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        fullname.setForeground(new java.awt.Color(0, 0, 0));
        fullname.setText("Full Name");

        tfFullname.setBackground(new java.awt.Color(255, 255, 255));
        tfFullname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tfFullname.setForeground(new java.awt.Color(0, 0, 0));

        phnum.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        phnum.setForeground(new java.awt.Color(0, 0, 0));
        phnum.setText("Phone Number");

        email.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        email.setForeground(new java.awt.Color(0, 0, 0));
        email.setText("E-mail Address");

        tfemail.setBackground(new java.awt.Color(255, 255, 255));
        tfemail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tfemail.setForeground(new java.awt.Color(0, 0, 0));
        tfemail.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
            }
            @Override
            public void focusLost(FocusEvent e) {
                checkEmail ce = new checkEmail();
                ce.start();
            }
        });

        text0.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        text0.setForeground(new java.awt.Color(0, 0, 0));
        text0.setText("Have you previously attended our facility");

        yes.setBackground(new java.awt.Color(204, 204, 204));
        yesno.add(yes);
        yes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        yes.setForeground(new java.awt.Color(0, 0, 0));
        yes.setText("Yes");
        yes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 255, 255), new java.awt.Color(51, 51, 51), null));

        no.setBackground(new java.awt.Color(204, 204, 204));
        yesno.add(no);
        no.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        no.setForeground(new java.awt.Color(0, 0, 0));
        no.setText("No");
        no.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 255, 255), new java.awt.Color(51, 51, 51), null));

        appoinment.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        appoinment.setForeground(new java.awt.Color(0, 0, 0));
        appoinment.setText("Appointment");

        date.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        date.setName("date\n"); // NOI18N
        date.setOpaque(false);

        time.setBackground(new java.awt.Color(204, 204, 204));
        time.setForeground(new java.awt.Color(0, 0, 0));
        time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30" }));
        time.setToolTipText("");
        time.setBorder(null);

        text1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        text1.setForeground(new java.awt.Color(0, 0, 0));
        text1.setText("Reason:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        try {
            tfPhnum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###) ###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        emailError.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        emailError.setForeground(new java.awt.Color(255, 0, 0));

        id.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        id.setForeground(new java.awt.Color(0, 0, 0));
        id.setText("ID:");

        tfid.setBackground(new java.awt.Color(255, 255, 255));
        tfid.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tfid.setForeground(new java.awt.Color(0, 0, 0));
        tfid.addFocusListener(new FocusListener()
        {
            @Override
            public void focusGained(FocusEvent event)
            {
            }
            @Override
            public void focusLost(FocusEvent event)
            {
                checkData cd = new checkData();
                cd.start();
            }
        });

        javax.swing.GroupLayout centerLayout = new javax.swing.GroupLayout(center);
        center.setLayout(centerLayout);
        centerLayout.setHorizontalGroup(
                centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(centerLayout.createSequentialGroup()
                                                  .addGap(20, 20, 20)
                                                  .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(centerLayout.createSequentialGroup()
                                                                                              .addComponent(jScrollPane1)
                                                                                              .addGap(15, 15, 15))
                                                                        .addGroup(centerLayout.createSequentialGroup()
                                                                                              .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                    .addComponent(fullname)
                                                                                                                    .addComponent(email)
                                                                                                                    .addComponent(phnum)
                                                                                                                    .addComponent(id))
                                                                                              .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                    .addGroup(centerLayout.createSequentialGroup()
                                                                                                                                          .addGap(52, 52, 52)
                                                                                                                                          .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                .addComponent(tfPhnum, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                .addGroup(centerLayout.createSequentialGroup()
                                                                                                                                                                                      .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                      .addGap(18, 18, 18)
                                                                                                                                                                                      .addComponent(emailError, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                .addComponent(tfid, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerLayout.createSequentialGroup()
                                                                                                                                                                                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                                      .addComponent(tfFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                              .addGap(0, 35, Short.MAX_VALUE))
                                                                        .addGroup(centerLayout.createSequentialGroup()
                                                                                              .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                    .addComponent(text0)
                                                                                                                    .addComponent(appoinment)
                                                                                                                    .addComponent(text1)
                                                                                                                    .addGroup(centerLayout.createSequentialGroup()
                                                                                                                                          .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                          .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                    .addGroup(centerLayout.createSequentialGroup()
                                                                                                                                          .addComponent(yes)
                                                                                                                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                          .addComponent(no)))
                                                                                              .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        centerLayout.setVerticalGroup(
                centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerLayout.createSequentialGroup()
                                                                                              .addContainerGap()
                                                                                              .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                    .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                                                                                                    .addComponent(tfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                              .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                    .addComponent(tfFullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                    .addComponent(fullname))
                                                                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                              .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                    .addComponent(phnum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                    .addComponent(tfPhnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                              .addGap(18, 18, 18)
                                                                                              .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                    .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                          .addComponent(email)
                                                                                                                                          .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                    .addComponent(emailError, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                              .addGap(16, 16, 16)
                                                                                              .addComponent(text0)
                                                                                              .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                    .addGroup(centerLayout.createSequentialGroup()
                                                                                                                                          .addGap(60, 60, 60)
                                                                                                                                          .addComponent(appoinment)
                                                                                                                                          .addGap(18, 18, 18)
                                                                                                                                          .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                                    .addGroup(centerLayout.createSequentialGroup()
                                                                                                                                          .addGap(18, 18, 18)
                                                                                                                                          .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                                                .addComponent(yes)
                                                                                                                                                                .addComponent(no))))
                                                                                              .addGap(18, 18, 18)
                                                                                              .addComponent(text1)
                                                                                              .addGap(18, 18, 18)
                                                                                              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                              .addGap(56, 56, 56))
        );

        getContentPane().add(center, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // Checkbox conditions
        String checked;
        if(yes.isSelected()) {
            checked = "YES";
        }
        else if(no.isSelected()){
            checked = "NO";
        }
        else {
            checked = "";
        }

        //Getting text fields
        String name, num, mail, text, day, code;
        name = tfFullname.getText();
        num = tfPhnum.getText();
        mail = tfemail.getText();
        text = jTextArea1.getText();
        String when = Objects.requireNonNull(time.getSelectedItem()).toString();
        code = tfid.getText();

        // Changing the JDateChooser Format
        DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
        if (date.getDate() == null) {
            day = "";
        } else {
            day = fmt.format(date.getDate()); // jdatechooser
        }

        // If no fields are filled in expect reason than a dialog box will appear
        if (!(code.contains("ID") || code.equals("000"))) {
            popup.coderror();
        }
        else if (name.equals("") || num.equals("(   )    -    ") || mail.equals("") || when.equals("") || day.equals("") || checked.equals("")) {
            popup.notice();
        }
        else if (!(mail.contains("@") && (mail.contains(".com") || mail.contains(".co") || mail.contains(".net") || mail.contains(".org") || mail.contains(".edu")))) {
            popup.emailnotice();
        }
        else {
            // creating Customer and connectMethod object
            Appointment user = new Appointment(code, name, num, mail, day, when, text, checked);
            connectMethod userData = new connectMethod();
            if (userData.openConnection()) {
                userData.insertAppointment(user);
                userData.closeConnection();
                popup.submit();
            }
            clearFields();
        }
    }//GEN-LAST:event_submitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appoinment;
    private javax.swing.JPanel center;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JPanel east;
    private javax.swing.JLabel email;
    static private javax.swing.JLabel emailError;
    private javax.swing.JLabel fullname;
    private javax.swing.JLabel id;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JCheckBox no;
    private javax.swing.JPanel north;
    private javax.swing.JLabel phnum;
    private javax.swing.JPanel south;
    private javax.swing.JButton submit;
    private javax.swing.JLabel text0;
    private javax.swing.JLabel text1;
    static private javax.swing.JTextField tfFullname;
    static private javax.swing.JFormattedTextField tfPhnum;
    static private javax.swing.JTextField tfemail;
    static private javax.swing.JTextField tfid;
    private javax.swing.JComboBox<String> time;
    private javax.swing.JLabel title;
    private javax.swing.JPanel west;
    private javax.swing.JCheckBox yes;
    private javax.swing.ButtonGroup yesno;
    // End of variables declaration//GEN-END:variables

    // Reset everything
    public void clearFields() {
        tfFullname.setText(null);
        tfemail.setText(null);
        tfPhnum.setValue(null);
        jTextArea1.setText(null);
        time.setSelectedIndex(0);
        date.setDate(null);
        yesno.clearSelection();
        emailError.setText(null);
        tfid.setText(null);
        tfFullname.requestFocusInWindow(); //Positions the cursor back in the number text field
    }// clearFields


    //Inner class for thread
    static class checkEmail extends Thread{
        public void run(){
            String e = tfemail.getText();
            if (e.contains("@") && (e.contains(".com") || e.contains(".co") || e.contains(".net") || e.contains(".org") || e.contains(".edu"))){
                emailError.setForeground(new Color(0, 255, 255));
                emailError.setText("Good Job");
            }
            else {
                emailError.setForeground(new Color(255, 0, 0));
                emailError.setText("@ and domain required");
            }
        }
    }

    //inner class that runs in the background
    static class checkData extends Thread{
        public void run()
        {
            connectMethod CusDAO = new connectMethod();
            if (CusDAO.openConnection())
            {
                try {
                    System.out.println("Thread is running....");
                    Customer thefind;
                    thefind = CusDAO.findCusRecord(tfid.getText());
                    CusDAO.closeConnection();
                    if (thefind != null) {
                        tfFullname.setText(thefind.getName());
                        tfPhnum.setText(thefind.getCell_num());
                        System.out.println(thefind.getCell_num());
                        tfemail.setText(thefind.getEmail());
                    }
                }catch (Exception e){
                    System.out.println("No match");
                }
            }
        }
    }
}
